[book]
language = "en"
multilingual = false
src = "documentation"
title = "Mina Fungible Token Documentation"
description = "Deploy and interact with custom fungible tokens on Mina."

[build]
build-dir = "target/documentation"
create-missing = false

[output.html]
copy-fonts = true
edit-url-template = "https://github.com/MinaFoundation/mina-fungible-token/edit/main/{path}"
git-repository-url = "https://github.com/MinaFoundation/mina-fungible-token"
no-section-label = false
preferred-dark-theme = "Coal"

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

