name: Documentation
permissions:
  pages: write
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: michaelfbryan/mdbook-docker-image
    steps:
    - uses: actions/checkout@v4
    - run: mdbook build
    - uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: ./target/documentation
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: documentation
          path: ./target/documentation
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/documentation


